### ISSUE TITLE
Archive errors.

### ISSUE THREAD

**Issue by cvantassle** [opensolutions/ViMbAdmin#239] opened 2018-01-25 05:29 UTC
I have marked several mailboxes for archiving and the cronjob is set up to run.
Now the accounts are marked in the frontend as "ARCHIVING"  however they never go past that. 
If I try to run the CRON job my self I get the listed errors

root@watchtower:/etc/cron.d# /var/www/vimbadmin/bin/vimbtool.php -a archive.cli-archive-pendings
sh: 1: cd: can't cd to vdclan.net/test//../
bzip2: Can't open input file /srv/archives/maildir-3.tar: No such file or directory.

I also get the same output if I run it with the -v or -d flags.

**Comment by barryo** [comment] 2018-01-29 16:13
Unfortunately there is not enough information here to help :-(

The paths seem to be wrong. Can you follow up on the mailing list with your `application/config/application.ini` settings up to but not beyond `Proceed onwards with caution.` excluding any sensitive settings.

I'm closing this here as this is not a bug. Mailing list details at: https://www.vimbadmin.net/support.php

**Closed by barryo** 2018-01-29 16:13 UTC
