### ISSUE TITLE
Cannot create same alias in different domains

### ISSUE THREAD

**Issue by ehooo** [opensolutions/ViMbAdmin#126] opened 2015-01-25 14:26 UTC
If you have a "postmaster@my.domain" and you want you create "postmaster@other.domain" is not posible at all.

I think this is the Fix for "doctrine2/xm/Entities.Alias.dcm.xml"
```
7   -    <field name="address" type="string" unique="true" length="255" nullable="false"/>
7   +    <field name="address" type="string" length="255" nullable="false"/>
17 +    <unique-constraints>
18 +        <unique-constraint columns="address,Domain_id" name="unique_email" />
19 +    </unique-constraints>
```

**Comment by barryo** [comment] 2015-01-26 07:02
@ehooo - I can't reproduce this. Furthermore, I have tons of the same aliases in different domains (obviously same user / local part, different domain).

Can you provide instructions to replicate on http://www.vimbadmin.net/demo/ ?

Closing pending reply.

**Closed by barryo** 2015-01-26 07:02 UTC

**Comment by ehooo** [comment] 2015-01-26 11:24
Sorry, my fault.
The fault is that you can not create any mail from a IP address.

http://www.vimbadmin.net/demo/mailbox/list/did/12
http://www.vimbadmin.net/demo/alias/list/did/12
